name: varseek
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - kat>=2.4.2
  - curl>=7.73.0
  - fastqc>=0.12.1
  - multiqc>=1.6
  - fastp>=0.23.4
  - bowtie2>=2.5.4
  - seqtk>=1.4
  - pip:
      - -r requirements.txt  # or use `pyproject.toml` for Python packages